project_id = "friyo"

[auth]
enable_anonymous_sign_ins = true

[functions.generate-meal-plan]
verify_jwt = true

[functions.regenerate-single-meal]
verify_jwt = true

[functions.generate-grocery-list]
verify_jwt = true
